### ISSUE TITLE
TaskQueue should be able to report the status of the task on the `ensure_block`

### ISSUE THREAD

**Issue by minuscorp** [fastlane/TaskQueue#3]
So in order to implement further retry policies and report results of a task, It'd be great to report the status of the executed task on the `ensure_block`, as it's always called, whether the task completed successfully or not.

**Comment by taquitos** [comment]
tracking in https://github.com/fastlane/TaskQueue/pull/4

**Comment by taquitos** [comment]
🎈🐐 🚀
